# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-validate}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ed Schmalzle"]
  s.date = %q{2009-11-16}
  s.description = %q{Rack middleware that validates HTML with w3c validator and displays result in page.}
  s.email = %q{Jonas714@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rack-validate.rb",
     "lib/rack-validate/validator.rb",
     "rack-validate.gemspec",
     "test/rack-validate_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/nerdEd/rack-validate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack middleware that validates HTML with w3c validator and displays result in page.}
  s.test_files = [
    "test/rack-validate_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<w3c_validator>, [">= 0.9.3]"])
    else
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<w3c_validator>, [">= 0.9.3]"])
    end
  else
    s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<w3c_validator>, [">= 0.9.3]"])
  end
end

